export const SET_LOGGED_IN = "SET_LOGGED_IN";
export const SET_LOGOUT = "SET_LOGOUT";

export const SHOW_GLOBAL_ALERT = "SHOW_GLOBAL_ALERT";
export const HIDE_GLOBAL_ALERT = "HIDE_GLOBAL_ALERT";

export const UPDATE_CHURCH = "UPDATE_CHURCH";
export const CREATE_CHURCH = "CREATE_CHURCH";

export const UPDATE_CHURCHES_LIST = "UPDATE_CHURCHES_LIST";
export const UPDATE_USER_FROM_CHURCH = "UPDATE_USER_FROM_CHURCH";

export const UPDATE_READY_TO_VOTE = "UPDATE_READY_TO_VOTE";
export const RESET_READY_TO_VOTE = "RESET_READY_TO_VOTE";

export const LIST_ALL_ELECTIONS = "LIST_ALL_ELECTIONS";

export const LIST_ALL_OPTIONS = "LIST_ALL_OPTIONS";

export const UPDATE_GENERAL_RESULTS = "UPDATE_GENERAL_RESULTS";
export const UPDATE_BY_CHURCHES_RESULTS = "UPDATE_BY_CHURCHES_RESULTS";
